services:
    # PHP Service
    app:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        container_name: ppob_app
        restart: unless-stopped
        volumes:
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
            - app-data:/var/www
        env_file:
            - .env
        depends_on:
            - db
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"
        healthcheck:
            test: ["CMD", "php", "artisan", "--version"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 30s

    # Nginx Service
    web:
        image: nginx:alpine
        container_name: ppob_web
        restart: unless-stopped
        ports:
            - "80:80"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
            - app-data:/var/www:ro
        depends_on:
            - app
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

    # PostgreSQL Service
    db:
        image: mysql:8.0
        container_name: ppob_db
        restart: unless-stopped
        environment:
            - MYSQL_DATABASE=mysql
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_USER=mysql
            - MYSQL_PASSWORD=mysql
        volumes:
            - mysql_data:/var/lib/mysql
        ports:
            - "3306:3306"
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
                max-file: "3"

volumes:
    mysql_data:
    app-data:
